name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          python builder.py

      - name: Rename output for OS
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
              mv dist/cloner.exe windows/cloner.exe
            elif [[ "${{ runner.os }}" == "macOS" ]]; then
              mv dist/cloner macOS/cloner
            else
              mv dist/cloner linux/cloner
            fi
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows/*
            macOS/*
            linux/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
